/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class App {

    public static void main(String[] args) {

        String filePath = "C:\\Users\\ahmad\\quotes\\app\\src\\main\\resources\\Q.json";




//        objectArray[0] = new Quote();
        try(BufferedReader bufferedReader = new BufferedReader(new FileReader(filePath))) {
            Quote [] allq = new Quote[5];
            Gson gson = new Gson();
            allq = gson.fromJson(bufferedReader, Quote[].class);
            int random = (int)Math.floor(Math.random() * (allq.length - 0 + 1) + 0);
            System.out.println(allq[random].toString());
        }
        catch (IOException e) {
            e.printStackTrace();
        }


    }
}
